#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output HDMI-2 --mode 3440x1440 --rate 60 --pos 0x0
xrandr --output VGA-1 --mode 1920x1200 --rate 60 --pos 0x0
xrandr --output VGA-1 --right-of HDMI-2 
nitrogen --restore
picom &
$HOME/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &

bspc config border_width         2
bspc config focused_border_color "#ca895f"
bspc config normal_border_color  "#808080"
bspc config window_gap           12

bspc monitor HDMI-2 -d I II III IV V  
bspc monitor VGA-1 -d VI VII VIII IX 

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding   	 40 

# Mice bindings
#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

#   Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

