# The theme colours can be an rgb string of the form "255, 255, 255" or a string that references the colours from your terminal theme: Reset, Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray, LightRed, LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White.
theme:
  active: Yellow
  #banner: White
  #error_border: Red
  #error_text: LightRed
  #hint: Yellow
  hovered: Blue
  inactive: Green
  #playbar_background: Black
  #playbar_progress: LightCyan
  #playbar_text: White
  selected: Red
  text: Green
  